#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ppdb
#    username: propick
#    password: propick
#  jpa:
#    show-sql: true
#    database: mysql
#    generate-ddl: false
#    properties:
#      hibernate:
#        format_sql: true
#
#  web:
#    resources:
#      static-locations: classpath:/static/, classpath:/public/

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/testdb
#    username: test
#    password: test
#  profiles:
#    active: admin
#  jpa:
#    show-sql: true
#    database: mysql
#    generate-ddl: false
#    properties:
#      hibernate:
#        format_sql: true
#
#  web:
#    resources:
#      static-locations: classpath:/static/, classpath:/public/

      spring:
        datasource:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/ppdb
          username: propick
          password: propick
        profiles:
          active: admin  # 기본 프로파일 설정
        jpa:
          show-sql: true
          database: mysql
          generate-ddl: false
          properties:
            hibernate:
              format_sql: true
        web:
          resources: { static-locations: "classpath:/static/, classpath:/public/, classpath:/resources/, classpath:/META-INF/resources/, classpath:/static/management/, file:uploads/" }
        servlet:
          multipart:
            enabled: true
            max-file-size: 10MB
            max-request-size: 10MB

      server:
        tomcat:
          uri-encoding: UTF-8

      # 관리자로 실행 시 주석 해제 후 사용
      # spring:
