spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ppdb
    username: propick
    password: propick
  jpa:
    show-sql: true
    database: mysql
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework: DEBUG
    com.ezen.propick: DEBUG

  # Thymeleaf 설정 추가
  thymeleaf:
    prefix: classpath:/templates/main/  # main 폴더를 포함한 경로 설정
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false